### ISSUE TITLE
When plugin is loaded stops Appium execution on closeApp() method in iOS

### ISSUE THREAD

**Issue by isaac-tribal** [AppiumTestDistribution/appium-reporter-plugin#111]
If you call an appium method that closes the App (to test an state when the App is closed and then open it for example), it throws an exception on the client side and stops the Appium server test execution **(breaking all the following tests)**

https://appium.io/docs/en/commands/device/app/close-app/

Code example:
`// Reload the app`
`driver.closeApp();`
`driver.launchApp();`

Client Exception:
`RequestError: socket hang up
    at ClientRequest.<anonymous> (node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.emit (node:domain:489:12)
    at ClientRequest.origin.emit (node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at Socket.socketOnEnd (node:_http_client:518:9)
    at Socket.emit (node:events:525:35)
    at Socket.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at connResetException (node:internal/errors:705:14)
    at Socket.socketOnEnd (node:_http_client:518:23)
    at Socket.emit (node:events:525:35)
    at Socket.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)`

Server Exception:
[appium-with-plugin.log](https://github.com/AppiumTestDistribution/appium-reporter-plugin/files/10700461/appium-with-plugin.log)

**Comment by Dileep17** [comment]
Might be bcz of a TODO which I'm yet to implement --  "expose the exclusion command list"

For every command plugin takes a screenshot and stores it for report. For `closeApp` and `launchApp` this will fail 🤦  . Currently, ExclusionList is [
  'createsession',
  'deletesession',
  'title',
  'screenshot',
  'status',
  'getreport',
];

will fix this.

**Comment by Dileep17** [comment]
@isaac-tribal should be fixed in 1.0.0-beta.12
Please let us know if you still face the problem
