### ISSUE TITLE
version 1.1.0-beta.01 breaks the javascript flow (1.0.0-beta.13 works fine)

### ISSUE THREAD

**Issue by isaac-tribal** [AppiumTestDistribution/appium-reporter-plugin#135]
GET /getReport
2023-05-05 22:02:26:922 [HTTP] {}
2023-05-05 22:02:26:943 uncaughtException: Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
    at Object.<anonymous> (/Users/isaactribal/.appium/node_modules/appium-reporter-plugin/lib/reporter.js:91:40)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/isaactribal/.appium/node_modules/appium-reporter-plugin/lib/reporter.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Attaching log from iOS:**

[appium-with-plugin-1.1.0-beta.01.log](https://github.com/AppiumTestDistribution/appium-reporter-plugin/files/11502910/appium-with-plugin-1.1.0-beta.01.log)

**Comment by Dileep17** [comment]
Hi @isaac-tribal version 1.1.0-beta.01 has a contract change and doesn't have backward compatibility. 

Based on logs /setTestInfo is still using old bindings which is supported only upto 1.0.0-beta-x 
```
2023-05-05 22:02:26:906 [HTTP] --> POST /session/46a7491b-47d3-4606-9e79-3ca4b8f6ed1b/setTestInfo
2023-05-05 22:02:26:906 [HTTP] {"testName":"should display first screen when app opens","testStatus":"passed","error":""}
```

From version 1.1.x /setTestInfo expects `sessionId` also. Check latest contact @ https://github.com/AppiumTestDistribution/appium-reporter-plugin#settestinfo

I should have made it more clear in release note or readme.

**Comment by Dileep17** [comment]
Please re-open if you still face issue after following new contract. Thanks!
